[global]
# Streamlit Cloud対応設定

[server]
# メモリ使用量を抑制
maxUploadSize = 50
maxMessageSize = 50

# パフォーマンス最適化
enableCORS = false
enableXsrfProtection = true

[browser]
# UI設定
gatherUsageStats = false

[theme]
# シンプルなテーマ
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"

[client]
# クライアント設定
showErrorDetails = false
