# .streamlit/config.toml - Streamlit configuration for FACS Data Analysis App

[server]
# Server configuration
port = 8501
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 100
maxMessageSize = 100
enableWebsocketCompression = false
runOnSave = false
fileWatcherType = "none"

[browser]
# Browser settings
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# Theme configuration matching FACS Data Analysis App
primaryColor = "#FF6B35"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
# Client configuration
caching = true
displayEnabled = true
showErrorDetails = true

[runner]
# Runner configuration
magicEnabled = true
installTracer = false
fixMatplotlib = true
postScriptGC = true
fastReruns = true

[deprecation]
# Deprecation warnings
showPyplotGlobalUse = false
showImageFormat = false

[ui]
# UI configuration
hideTopBar = false
hideSidebarNav = false

[global]
# Development mode settings
developmentMode = false
logLevel = "info"
unitTest = false
